language: node_js
node_js:
- node
deploy:
  provider: npm
  email: adel.mehrban@gmail.com
  api_key:
    secure: N7fAyrv7QlGubuGQM7hET3YPhqUwBKqjL8TTRbmYIyjjwly4EirdNy2b4ZHirnzcXfs28eg7j8OX0RXxd2AsCX/XzcqzH2mf3tinGMC2c0MdhIqkVQb3Zbw438qDpCp6qj+PxcRrT8dMM4pkYBq9Ueqs6+iKArbVNMtQbNqaGvRTCyR9PWXyMTdo5rbMuDSktxHnIY9YSEDoIcfypghhaJ62MHYLW2VVYegw09BMTvqlnwII7PprOYVBpPbq754qkDI6TNYPOyf3wCItLfnqjlO9mUXq9XS0mGVKvnTDDSXfnS7CvuY3y5tzEMGSNGVvusIFPQPgROhqXCknyB5f20zB0zxiKJKuICKvKaOa1vhrZK/YjuQoO/YFEJGVahQU9obsjPlQ2SUyUJR7qbDTjyRaa4jKybh1fUKD1V+lFD5BmZoOGnggYKtP7Sdq5kmpFU3rEsUv+NgyrBUqY6bYzZpW5VT0zLfmufxqoyegkdP4qQQb4uwG/lySMHeqKC4WAaS8iArgknb2eAVN/3BmMSUwK5xXIkmferG7aSA4G+UEOxRN4unenyg5POSB1mp8q7QY/2XgZ/hVEzJNzwcFQqKK49/alTz44dEpFyCci1YO00WVcUqrYMgXVklAX04mZCJllWIifAivBhtqIZINjRTFbxlmmtMzsfcab75Axes=
  skip_cleanup: true
